In [7]:
"""import sqlalchemy as sqal

server = 'localhost,1433'
database = 'Northwind'
user = 'SA'
password = 'Passw0rd2018'
driver = 'ODBC+Driver+17+for+SQL+Server'

engine = sqal.create_engine(f"mssql+pyodbc://{user}:{password}@{server}/{database}?driver={driver}")
"""
print('done')

done


markdown example

# headings
## subheadings
plain text

In [1]:
import numpy as np
import pandas as pd
print('done')

done


In [8]:
list1 = [1,2,3]
arr1 = np.array(list1)

list2 = [4,5,6]
arr2 = np.array(list2)

list3 = [list1,list2]
arr3 = np.array(list3)
print(arr3)

[[1 2 3]
 [4 5 6]]


In [13]:
list4 = [[list1,list2],[list1,list2]]
arr4 = np.array(list4)
print(arr4.shape)
print(arr4)

(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
print(list1*3)
print(arr1*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [17]:
arr5 = np.arange(1,6)
print(arr5)
print(arr1*arr2)

[1 2 3 4 5]
[ 4 10 18]


In [18]:
print(arr1*arr5)

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [19]:
print(arr1*arr4)

[[[ 1  4  9]
  [ 4 10 18]]

 [[ 1  4  9]
  [ 4 10 18]]]


In [41]:
# create n-dimensional arrays:

# 1d, x12
list_1d = [i for i in range(1,13)]
arr_1d = np.array(list_1d)
print('\n1d array:',arr_1d.shape,'\n',arr_1d)

# 2d, 3x4
len_res = 4
arr_1st3rd = np.array(list_1d[0:len_res])
arr_2nd3rd = np.array(list_1d[len_res:len_res+4])
arr_3rd3rd = np.array(list_1d[len_res+4:len_res+8])
#arr_2d = np.array([list_1st3rd,list_2nd3rd,list_3rd3rd])
list_2d = [arr_1st3rd,arr_2nd3rd,arr_3rd3rd]
arr_2d = np.array(list_2d)
print('\n2d array:',arr_2d.shape,'\n',arr_2d)

# 3d, 2x5x4
print(arr_1st3rd*3)
list_3d = []
for i in range(5):
    list_3d.append(list_2d)
arr_3d = np.array(list_3d)
print('\n3d array:',arr_3d.shape,'\n',arr_3d)


1d array: (12,) 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

2d array: (3, 4) 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 3  6  9 12]

3d array: (5, 3, 4) 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [48]:
print(arr_2d[:,1])
print(arr_2d.max())
for i in np.nditer(arr_2d):
    print(i)

[ 2  6 10]
12
1
2
3
4
5
6
7
8
9
10
11
12
